# Generated by Django 5.2.4 on 2025-07-10 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('tipo', models.CharField(choices=[('Bebida', 'Bebida'), ('Principal', 'Principal'), ('Postre', 'Postre')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['dia_semana', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.TextField()),
                ('instrucciones', models.TextField()),
                ('platillo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='platillos.platillo')),
            ],
        ),
    ]
