# Generated by Django 5.2.4 on 2025-07-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platillos', '0002_remove_receta_instrucciones'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platillo',
            unique_together={('dia_semana',)},
        ),
    ]
