# Generated by Django 5.2.4 on 2025-07-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platillos', '0003_alter_platillo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platillo',
            unique_together={('dia_semana', 'tipo')},
        ),
    ]
